### PR TITLE
fix(*): brute force initial conversion to TS

### PR DESCRIPTION
**Pull request by JamesHenry**
Deliberately approached this large PR as a first step - force the tsc to compile the codebase successfully _without_ making runtime changes to it.

E.g. in a code path which is currently exposed to possible unaccounted for null values, and would therefore be flagged by `strictNullChecks`, the solution in this PR is to use type assertions/casting. In follow up PRs the underlying issues will be fixed.

I have painstakingly recreated the ESTree spec (type info from that not yet in use though to align with the above intentions).

Yuck:
- A million type assertions
- Temporary inferred type info from legacy JS codebase is very funky

Yay:
...but up and running with TypeScript source 🎉

### CODE REVIEW

**Comment by JamesHenry** [comment]
I have updated the commit to be a `fix` so that a patch release update will be triggered by semantic-release and the updated build/publish process can be validated

**Comment by j-f1** [comment]
FYI there’s a `@types/estree` package

**Comment by kaicataldo** [comment]
Nice work!

**Pull request merged**
