### PR TITLE
BREAKING: correct nodes TSConstructorType and TSConstructorType

### PR DESCRIPTION
**Pull request by armano2**
This PR contains breaking changes and its alternative way of solving issue #30

Changes from this PR align structure of AST with what babel produces.
There is alternative version of aligning those nodes #60

-------

babel parses `CallSignature` and `ConstructSignature` as `TSCallSignatureDeclaration` and `TSConstructSignatureDeclaration` and has fields:

  ```ts
  interface foo {
    <P>(x: X): A
  }
  ````
- `typeParameters` typeParameters
- `parameters` array of all parameters
- `typeAnnotation` expected return type of function

right now we are parsing it as `typeParameters`, (`params` or `parameters`) and `typeAnnotation`

fixes: #30, #60

### CODE REVIEW

**Comment by armano2** [comment]
i'm unsure how we should proceed with this, do we want to have same structure as babel for this? or we want to align it to how names are provided in estree...

**Comment by JamesHenry** [comment]
Yeah it's a tricky one for sure. The inconsistency on the babel side makes me think that maybe we should forgo compatibility on this one and just make a clear note that we need to fix it up on the babel side later.

There have been plenty of cases over the last year or so that I flagged up or fixed odd things on the babel side after discovering them through the ast-alignment testing, so it is not entirely unexpected.

What do you think?

**Comment by armano2** [comment]
I'm OK with changingnames of propertiesbut I feel like we should keep name of node as babel

**Comment by JamesHenry** [comment]
Sounds good 👍

**Comment by armano2** [comment]
ok i'm closing than #60 and i will rebase change here

**Pull request merged**
