### PR TITLE
fix(ast): fix wrong node type on literal expressions

### LINKED ISSUE #8: Wrong AST type in LHS of AssignmentExpression
Port of https://github.com/eslint/typescript-eslint-parser/issues/467

### PR DESCRIPTION
**Pull request by g-plane**
Same as https://github.com/eslint/typescript-eslint-parser/pull/509

Fix #8

### CODE REVIEW

**Comment by JamesHenry** [comment]
Apologies, @g-plane, I suddenly realised I hadn't been checking the commit format. I have now set up linting for it, it should follow the conventional changelog style:

```type(scope?): subject
body?
footer?```

This is because I release automatically using semantic-release

**Comment by g-plane** [comment]
Maybe I just need to update the PR title? Then, you can squash and merge it.

**Comment by JamesHenry** [comment]
I really appreciate the quick response (caught me a little off guard how prompt you were! :D ), I have since added formatting with prettier to the repo.

Both the formatting and the commit messages are checked as part of the build now. I would feel more comfortable getting everything up to date and having a passing build before merging please.

Also please remember to add the `BREAKING` back in the commit body, in this commit style it is not represented in the subject, it is in the commit body.

You can use the `cz` npm script to use an interactive prompt to build the commit message too just FYI

**Comment by JamesHenry** [comment]
Sorry again that I made extra work for you on this

**Comment by g-plane** [comment]
@JamesHenry Updated.

**Comment by JamesHenry** [comment]
Thanks again @g-plane!

**Pull request merged**
