### PR TITLE
feat(diagnostics): report on TS 1049, TS 1211 and TS 2364

### PR DESCRIPTION
**Pull request by JamesHenry**

### CODE REVIEW

**Comment by armano2** [comment]
@j-f1 its good point, if we are not planning to add extra conditions there, we should go for `includes`, it has better performance.

https://jsperf.com/indexof-vs-switch-vs-includes

**Comment by j-f1** [comment]
Oh wow switch is much faster

**Comment by armano2** [comment]
did you tested it on chrome? -> we are targeting v8 (node) and `includes` is faster there

image

**Pull request merged**
